spring.application.name=FinanceHub

spring.datasource.url=jdbc:mysql://localhost:3306/financehub

spring.datasource.username=root
spring.datasource.password=nishwan810

spring.jpa.hibernate.ddl-auto=update